import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {chromium} from 'playwright';
import {writeFile} from 'node:fs/promises';
let browser,server;const checks=[],base='http://127.0.0.1:4198';
before(async()=>{server=spawn(process.execPath,['node_modules/vite/bin/vite.js','preview','--host','127.0.0.1','--port','4198'],{stdio:'ignore'});for(let i=0;i<50;i++){try{if((await fetch(base)).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}browser=await chromium.launch({executablePath:process.env.ZY_CHROMIUM_PATH,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});});
after(async()=>{await browser?.close();server?.kill();await writeFile('docs/evidence/P3_7B_SHOWCASE.json',JSON.stringify({date:new Date().toISOString(),environment:'Chromium / SwiftShader viewport emulation; not physical device acceptance',checks},null,2));});
async function open(width=1440,reduced=false){const p=await browser.newPage({viewport:{width,height:1000},hasTouch:width<700,isMobile:width<700,reducedMotion:reduced?'reduce':'no-preference'});await p.goto(base);await p.locator('.brand-showcase').scrollIntoViewIfNeeded();await p.waitForFunction(()=>document.querySelector('[data-showcase-stage]').dataset.state==='ready');await p.waitForTimeout(150);return p;}
const state=p=>p.locator('[data-showcase-stage]').evaluate(e=>({...e.dataset}));
test('360 degree drag, keyboard rotation, light toggle, idle/offscreen and responsive view',async()=>{for(const width of [1440,360]){const p=await open(width);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));const initial=await state(p);await p.locator('[data-van-turn="1"]').click();await p.waitForTimeout(120);assert.ok(Number((await state(p)).angle)>Number(initial.angle));await p.locator('[data-van-turn="1"]').press('ArrowRight');await p.waitForTimeout(100);assert.ok(Number((await state(p)).angle)>Number(initial.angle)+.7);await p.locator('[data-van-reset]').click();await p.waitForTimeout(100);assert.equal((await state(p)).angle,'-0.45');
 await p.locator('[data-box-light]').click();await p.waitForTimeout(100);assert.equal((await state(p)).light,'false');await p.locator('[data-box-light]').click();
 await p.locator('[data-showcase-stage]').scrollIntoViewIfNeeded();const b=await p.locator('[data-showcase-stage]').boundingBox();const x=b.x+b.width*(width<700?.5:.69),y=b.y+b.height*(width<700?.65:.65);
 if(width===1440){await p.mouse.move(x,y);await p.mouse.down();await p.mouse.move(x+110,y,{steps:6});await p.mouse.up();}else{const c=await p.context().newCDPSession(p);await c.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});await c.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+65,y}]});await c.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}
 await p.waitForTimeout(200);assert.notEqual((await state(p)).angle,'-0.45');await p.locator('[data-van-reset]').click();await p.locator('[data-showcase-stage]').scrollIntoViewIfNeeded();await p.waitForTimeout(200);const idle=await state(p);await p.waitForTimeout(250);assert.equal((await state(p)).frames,idle.frames);await p.locator('.brand-showcase').screenshot({path:`docs/evidence/showcase-${width}.png`});
 if(width===360)await p.locator('[data-showcase-stage]').screenshot({path:'public/assets/showcase/mobile.png'});
 await p.evaluate(()=>scrollTo(0,document.body.scrollHeight));await p.waitForTimeout(100);const off=await state(p);await p.waitForTimeout(200);assert.equal((await state(p)).frames,off.frames);checks.push({width,drag:true,keyboard:true,light:true,idle:true,offscreen:true,overflow:false});await p.close();}});
test('Reduced motion manual controls and context fallback preserve content',async()=>{const p=await open(360,true);await p.locator('[data-van-turn="1"]').click();await p.waitForTimeout(100);assert.notEqual((await state(p)).angle,'-0.45');await p.locator('[data-showcase-mount] canvas').evaluate(c=>c.dispatchEvent(new Event('webglcontextlost',{cancelable:true})));await p.waitForFunction(()=>document.querySelector('[data-showcase-stage]').dataset.state==='fallback');assert.equal(await p.locator('.brand-showcase-poster').evaluate(i=>i.complete&&i.naturalWidth>0),true);assert.equal(await p.locator('[data-showcase-mount] canvas').count(),0);assert.equal(await p.locator('[data-van-turn="1"]').isDisabled(),true);checks.push({reducedMotion:true,contextFallback:true});await p.close();});
