import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {chromium} from 'playwright';
import {writeFile} from 'node:fs/promises';
let browser,server;const checks=[],base='http://127.0.0.1:4198';
before(async()=>{server=spawn(process.execPath,['node_modules/vite/bin/vite.js','preview','--host','127.0.0.1','--port','4198'],{stdio:'ignore'});for(let i=0;i<50;i++){try{if((await fetch(base)).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}browser=await chromium.launch({executablePath:process.env.ZY_CHROMIUM_PATH,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});});
after(async()=>{await browser?.close();server?.kill();await writeFile('docs/evidence/P3_7C_REAL_REFERENCES.json',JSON.stringify({checks,vehicle360:'actual Nissan GLB, user-controlled continuous 360 degrees',modelBytes:4110300},null,2));});
test('Actual reference lightbox lights distinctly on hover, keyboard and touch; responsive photographs',async()=>{for(const width of [1440,360]){const p=await browser.newPage({viewport:{width,height:1000},hasTouch:width<700,isMobile:width<700});await p.goto(base);await p.locator('#marka-vitrini').scrollIntoViewIfNeeded();await p.locator('[data-real-lightbox] img').evaluate(i=>i.decode());await p.locator('.real-car-reference img').evaluate(i=>i.decode());const light=p.locator('[data-real-lightbox]');const normal=await light.locator('img').evaluate(i=>getComputedStyle(i).filter);if(width===1440){await light.hover();assert.equal(await light.getAttribute('data-lit'),'true');await p.waitForTimeout(350);const bright=await light.locator('img').evaluate(i=>getComputedStyle(i).filter);assert.notEqual(normal,bright);await p.locator('#marka-vitrini').screenshot({path:'docs/evidence/real-lightbox-hover.png'});await p.mouse.move(0,0);assert.equal(await light.getAttribute('data-lit'),'false');}await p.locator('[data-box-light]').focus();assert.equal(await light.getAttribute('data-lit'),'true');await p.locator('[data-box-light]').click();assert.equal(await p.locator('[data-box-light]').getAttribute('aria-pressed'),'true');assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await p.locator('#marka-vitrini').screenshot({path:`docs/evidence/real-references-${width}.png`});checks.push({width,photosDecoded:true,keyboard:true,touchControl:true,hover:width===1440,overflow:false});await p.close();}});
test('JavaScript and WebGL independent photographs; reduced motion retains illumination',async()=>{for(const js of [true,false]){const p=await browser.newPage({viewport:{width:360,height:1000},javaScriptEnabled:js,reducedMotion:'reduce'});await p.goto(base);await p.locator('#marka-vitrini').scrollIntoViewIfNeeded();await p.locator('[data-real-lightbox] img').evaluate(i=>i.decode());assert.equal(await p.locator('#marka-vitrini canvas').count(),0);if(js){await p.locator('[data-box-light]').click();assert.equal(await p.locator('[data-real-lightbox]').getAttribute('data-lit'),'true');}checks.push({javaScript:js,photographicFallback:true,vehicle360PosterUntilExplicitLoad:true});await p.close();}});

test('Actual Nissan rotates freely, keyboard/reset, touch, idle/offscreen and context fallback',async()=>{
 for(const width of [1440,360]){
  const p=await browser.newPage({viewport:{width,height:1000},hasTouch:width===360,isMobile:width===360,reducedMotion:width===360?'reduce':'no-preference'});
  const errors=[];p.on('pageerror',e=>errors.push(e.message));let modelRequests=0;p.on('request',r=>{if(r.url().endsWith('nissan-t32.glb'))modelRequests++;});
  await p.goto(base);const stage=p.locator('[data-vehicle-stage]');await stage.scrollIntoViewIfNeeded();assert.equal(modelRequests,0);await p.locator('[data-vehicle-load]').click();await p.waitForFunction(()=>document.querySelector('[data-vehicle-stage]').dataset.state==='ready',null,{timeout:30000});await p.waitForTimeout(400);assert.equal(modelRequests,1);assert.equal(await stage.locator('canvas').count(),1);
  const initial=Number(await stage.getAttribute('data-angle'));for(let i=0;i<13;i++)await p.locator('[data-van-turn="1"]').click();await p.waitForTimeout(100);assert.ok(Number(await stage.getAttribute('data-angle'))-initial>2*Math.PI);
  await p.locator('[data-van-reset]').click();await p.waitForTimeout(100);assert.ok(Math.abs(Number(await stage.getAttribute('data-angle'))-initial)<.001);await stage.focus();await p.keyboard.press('ArrowRight');await p.waitForTimeout(100);assert.notEqual(Number(await stage.getAttribute('data-angle')),initial);await p.keyboard.press('Home');
  const box=await stage.boundingBox();if(width===1440){await p.mouse.move(box.x+box.width*.35,box.y+box.height*.5);await p.mouse.down();await p.mouse.move(box.x+box.width*.7,box.y+box.height*.5,{steps:12});await p.mouse.up();}else{const cdp=await p.context().newCDPSession(p);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:box.x+70,y:box.y+box.height/2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:box.x+210,y:box.y+box.height/2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await cdp.detach();}await p.waitForTimeout(200);assert.ok(Math.abs(Number(await stage.getAttribute('data-angle'))-initial)>.5);
  await p.locator('[data-van-reset]').click();await p.locator('[data-box-light]').click();await p.waitForTimeout(300);await p.locator('#marka-vitrini').screenshot({path:`docs/evidence/real-nissan-${width}.png`});
  const frames=await stage.getAttribute('data-frames');await p.waitForTimeout(350);assert.equal(await stage.getAttribute('data-frames'),frames);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await p.evaluate(()=>scrollTo(0,0));await p.waitForTimeout(250);await p.locator('[data-van-turn="1"]').evaluate(b=>b.click());await p.waitForTimeout(200);assert.equal(await stage.getAttribute('data-frames'),frames);
  await stage.scrollIntoViewIfNeeded();await p.waitForTimeout(250);
  await p.locator('[data-vehicle-load]').click();assert.equal(await stage.getAttribute('data-state'),'poster');assert.equal(await stage.locator('canvas').count(),0);assert.equal(await p.locator('[data-vehicle-load]').getAttribute('aria-expanded'),'false');assert.equal(await p.locator('[data-van-turn="1"]').isDisabled(),true);await p.locator('.real-car-reference img').evaluate(i=>i.decode());
  await p.locator('[data-vehicle-load]').press('Enter');await p.waitForFunction(()=>document.querySelector('[data-vehicle-stage]').dataset.state==='ready',null,{timeout:30000});assert.equal(await p.locator('[data-vehicle-load]').getAttribute('aria-expanded'),'true');await p.waitForTimeout(250);await stage.locator('canvas').evaluate(c=>c.getContext('webgl2').getExtension('WEBGL_lose_context').loseContext());await p.waitForTimeout(250);assert.equal(await stage.getAttribute('data-state'),'poster');assert.equal(await stage.locator('canvas').count(),0);assert.equal(errors.length,0);
  checks.push({width,modelLoaded:true,continuous360:true,keyboard:true,drag:true,idleStopped:true,offscreenStopped:true,contextFallback:true,closeAndReopen:true,errors});await p.close();
 }
});
test('Failed model download preserves the actual reference and offers retry',async()=>{const p=await browser.newPage();await p.route('**/nissan-t32.glb',r=>r.abort());await p.goto(base);await p.locator('[data-vehicle-load]').click();await p.waitForFunction(()=>document.querySelector('[data-vehicle-stage]').dataset.state==='poster');assert.equal(await p.locator('[data-vehicle-load]').isEnabled(),true);await p.locator('.real-car-reference img').evaluate(i=>i.decode());checks.push({modelFailureFallback:true});await p.close();});
