import { WebGLRenderer, Scene, PerspectiveCamera, HemisphereLight, DirectionalLight, Mesh, PlaneGeometry, ShadowMaterial, PMREMGenerator, ACESFilmicToneMapping, Raycaster, Vector2, type Material } from 'three';
import { RoomEnvironment } from 'three/addons/environments/RoomEnvironment.js';
import { createVan,createLightbox } from './models';
export function createShowcase(stage:HTMLElement,onFailure:()=>void){
 const renderer=new WebGLRenderer({alpha:true,antialias:true,powerPreference:'low-power'}),canvas=renderer.domElement;
 canvas.setAttribute('aria-hidden','true');renderer.toneMapping=ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;renderer.shadowMap.enabled=true;
 const scene=new Scene(),camera=new PerspectiveCamera(36,1,.1,60),pm=new PMREMGenerator(renderer),room=new RoomEnvironment(),env=pm.fromScene(room);scene.environment=env.texture;room.dispose();pm.dispose();
 scene.add(new HemisphereLight('#ffefd6','#183d33',2.5));const key=new DirectionalLight('#fff1de',3.4);key.position.set(1,7,8);key.castShadow=true;key.shadow.mapSize.set(512,512);key.shadow.camera.left=-9;key.shadow.camera.right=9;key.shadow.camera.top=7;key.shadow.camera.bottom=-7;scene.add(key);const rim=new DirectionalLight('#abd9d0',2);rim.position.set(-5,4,-4);scene.add(rim);
 const van=createVan(),box=createLightbox();scene.add(van.group,box.group);const ground=new Mesh(new PlaneGeometry(30,30),new ShadowMaterial({opacity:.28}));ground.rotation.x=-Math.PI/2;ground.position.y=-2.26;ground.receiveShadow=true;scene.add(ground);
 let visible=false,disposed=false,raf=0,drag:number|null=null,start=0,angle=van.group.rotation.y,light=true;const abort=new AbortController();
 const reduced=()=>document.documentElement.dataset.motion==='reduced'||matchMedia('(prefers-reduced-motion: reduce)').matches;
 function draw(){if(disposed||!visible||document.hidden)return;renderer.render(scene,camera);stage.dataset.angle=String(van.group.rotation.y);stage.dataset.frames=String(Number(stage.dataset.frames||0)+1);stage.dataset.light=String(light);}
 function requestDraw(){if(!raf&&visible&&!disposed)raf=requestAnimationFrame(()=>{raf=0;draw();});}
 function resize(){const r=stage.getBoundingClientRect(),mobile=r.width<700;renderer.setPixelRatio(Math.min(devicePixelRatio,mobile?1.15:1.5));renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;
 van.group.position.set(mobile?0:1.8,mobile?-2.25:-2.25,0);van.group.scale.setScalar(mobile?.73:.95);box.group.position.set(mobile?0:-3.4,mobile?3:0,0);box.group.scale.setScalar(mobile?.87:1);
 const h=Math.max(mobile?11.9:6.1,(mobile?5.2:11.5)/camera.aspect);camera.position.set(0,mobile?.45:.4,h/(2*Math.tan(Math.PI/10)));camera.lookAt(0,mobile?.45:0,0);camera.updateProjectionMatrix();requestDraw();}
 const ray=new Raycaster(),pointer=new Vector2();
 canvas.addEventListener('pointerdown',e=>{if(!visible)return;const r=canvas.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,1-(e.clientY-r.top)/r.height*2);ray.setFromCamera(pointer,camera);if(ray.intersectObject(van.group,true).length){drag=e.pointerId;start=e.clientX;angle=van.group.rotation.y;canvas.setPointerCapture(e.pointerId);canvas.style.cursor='grabbing';}},{signal:abort.signal});
 canvas.addEventListener('pointermove',e=>{if(drag===e.pointerId){van.group.rotation.y=angle+(e.clientX-start)*.012;requestDraw();}},{signal:abort.signal});
 const release=()=>{drag=null;canvas.style.cursor='grab';};canvas.addEventListener('pointerup',release,{signal:abort.signal});canvas.addEventListener('pointercancel',release,{signal:abort.signal});canvas.addEventListener('lostpointercapture',release,{signal:abort.signal});canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();onFailure();},{signal:abort.signal});
 const controls=stage.closest('section')!;controls.querySelectorAll<HTMLElement>('[data-van-turn]').forEach(b=>b.addEventListener('click',()=>{van.group.rotation.y+=Number(b.dataset.vanTurn)*Math.PI/6;requestDraw();},{signal:abort.signal}));
 controls.querySelector('[data-van-reset]')?.addEventListener('click',()=>{van.group.rotation.y=-.45;requestDraw();},{signal:abort.signal});
 const lighting=controls.querySelector<HTMLButtonElement>('[data-box-light]');lighting?.addEventListener('click',()=>{light=!light;box.faceMat.emissiveIntensity=light?.85:0;lighting.setAttribute('aria-pressed',String(light));lighting.textContent=light?'Işığı kapat':'Işığı aç';requestDraw();},{signal:abort.signal});
 controls.querySelector('[data-van-keyboard]')?.addEventListener('keydown',e=>{const k=e as KeyboardEvent;if(k.key==='ArrowLeft'||k.key==='ArrowRight'){k.preventDefault();van.group.rotation.y+=(k.key==='ArrowLeft'?-1:1)*Math.PI/12;requestDraw();}if(k.key==='Home'){k.preventDefault();van.group.rotation.y=-.45;requestDraw();}},{signal:abort.signal});
 const ro=new ResizeObserver(resize);ro.observe(stage);stage.querySelector('[data-showcase-mount]')!.append(canvas);resize();stage.dataset.motion=reduced()?'reduced':'full';
 return {setVisible(v:boolean){visible=v;if(!v){cancelAnimationFrame(raf);raf=0;release();}else requestDraw();},dispose(){if(disposed)return;disposed=true;cancelAnimationFrame(raf);abort.abort();ro.disconnect();const geometries=new Set<import('three').BufferGeometry>(),materials=new Set<Material>();scene.traverse(o=>{if(o instanceof Mesh){geometries.add(o.geometry);(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>materials.add(m));}});geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());[...van.textures,...box.textures].forEach(t=>t.dispose());env.dispose();key.shadow.dispose();renderer.dispose();renderer.forceContextLoss();canvas.remove();}};
}
